### PR TITLE
Fix bug of generated code of selectOption. 

### PR DESCRIPTION
**Pull request by jaceju**
It should be `->` not `.`.

### CODE REVIEW

**Comment by sorich87** [comment]
Thanks!

**Comment by jaceju** [comment]
@sorich87 Thank you for accepted the PR.
Can your merge the branch to master?

**Comment by sorich87** [comment]
It has already been merged to master. https://github.com/sorich87/phpunitwdformatter/commits/master Am I missing something?

**Comment by jaceju** [comment]
@sorich87 Sorry, It's my misunderstanding.

**Pull request merged**
